XML Reader Implementation
noahpy/MolSim-SS24 pull request #27
Opened 2024-05-21 19:39 UTC by noahpy

2024-05-21 19:47 UTC, jimin31 approved these changes

2024-05-23 05:28 UTC, Chryzl requested changes
Sieht echt super heftig aus, Respekt dafür schonmal

Eine Frage habe ich allerdings. So wie ich die `.xsd` Datei verstehe, lesen wir bisher nicht 
> Base name and write frequency of output files
ein, oder sehe ich das falsch? Das soll nach Aufgabenstellung noch gemacht werden. Vllt kannst du das hinzufügen, sonst gucke ich es mir gerne nochmal an, nur das wir es auf dem Schirm haben

2024-05-23 06:12 UTC, noahpy commented
Ne hast du absolut recht, wird noch gemacht :)

2024-05-25 00:45 UTC, Chryzl approved these changes
LGTM!

2024-05-25 10:59 UTC, merged