Added a sphere cluster
noahpy/MolSim-SS24 pull request #28
Opened 2024-05-23 05:13 UTC by Chryzl

This code generates a sphere cluster.

Supports both 2D and 3D cases.

A sphere is a stack of discs that are a cumulation of circles.

Move validation of dimensionality to parent class.

2024-05-23 08:34 UTC, noahpy requested changes
Auf jeden fall sehr stark gemacht und die Idee mit den Ringen / Disks ist schon sehr nice.
Hier und da paar Sachen die mir aufgefallen sind, aber korrigiere mich ruhig wenn ich etwas nicht ganz verstanden habe :)
Ansonsten würde ich den neuen Cluster zum ClusterReader hinzufügen, dass man auch sieht wie es in einer Simulation aussieht, das kann ich gerne machen

2024-05-23 08:34 UTC, noahpy commented on src/models/generators/ParticleCluster.cpp
> +    }
Ich finde hier könnte man alle `dimensions` zwischen 0 und 3 zulassen, z.B. wenn man einfach mal die Brownian motion "ausschalten" will. Was würdest du sagen? Also dann:
```suggestion
    if (dimensions > 3) {
        spdlog::warn(
            "The dimensions specified for the brownian motion of a particle cluster was set to {}. "
            "It can only be of values smaller equal three",
            dimensions);
        throw std::invalid_argument("Dimensions must be smaller equal 3.");
    }
```

2024-05-23 08:34 UTC, noahpy commented on src/models/generators/SphereParticleCluster.cpp
> +            radianAngle += step;
Das hier ist wirklich nice. 
Ein Sphere besteht aus Kreisen, ein Kreis aus Ringe!

2024-05-23 08:34 UTC, noahpy commented on tests/simulation/testSphereParticleGenerator.cpp
> +        }
Hier schaust du ob die Distanz innerhalb 5% zusätzlich liegt, aber um zu testen ob die Partikel innerhalb der allgemeinen 5% bleiben, müssen wir auch von unten vergleichen (solange ich das richtig verstanden habe):
```suggestion
        if (iteration++ % 10 == 0) {
            // Check if distance is leq than 105% of the radius
            for (auto& p : container) {
                double dist = ArrayUtils::L2Norm(p.getX() - origin);
                EXPECT_LE(dist, radius * spacing * tolerance) << "Particle breached upper tolerance!";
                EXPECT_GE(dist, radius * spacing * 0.95) << "Particle breached lower tolerance!";
            }
        }
```
Vielleicht noch die 0.95 in eine Variable packen, oder `tolerance` auf 0.05 setzen und dann mit `(1+tolerance)` und `(1-tolerance)` rechnen.

2024-05-23 08:34 UTC, noahpy commented on tests/simulation/testSphereParticleGenerator.cpp
> +                EXPECT_LE(dist, radius * spacing * tolerance);
Das gleiche dann hier, also man muss auch von unten checken. 
Das Problem ist aber auch, dass sowas von Epsilon, Spacing und Sigma abhängt, aber an sich ergibt der Test schon Sinn :)

2024-05-23 13:48 UTC, jimin31 approved these changes

2024-05-24 07:32 UTC, Chryzl commented on tests/simulation/testSphereParticleGenerator.cpp
> +        }
Das Problem ist, dass wenn man es so testet, dann hat man quasi nur eine Hülle
Also quasi eine Schicht, in der alle Teilchen sein dürfen und die hat eine Breite von 10% des gesamt Radius

Unsere Spheres sind aber solide, heißt die gehen bis ins Zentrum (origin)

<img width="257" alt="image" src="https://github.com/noahpy/MolSim-SS24/assets/56398851/ad317519-1ba3-4fff-9c36-9d6f1085fd44">

Mit dem Test wollte ich nur schauen, ob die Kugel an sich stabil ist und nicht einfach "explodiert"
Macht das Sinn?

2024-05-25 10:57 UTC, noahpy requested changes

2024-05-25 10:57 UTC, noahpy commented on tests/simulation/testSphereParticleGenerator.cpp
> +        }
Ah ja ok ergibt schon Sinn :)

2024-05-25 10:57 UTC, noahpy commented on src/models/generators/SphereParticleCluster.cpp
> +
Hier haben wir ein Problem:
Der Radius nimmt nicht linear mit dem offset ab, sondern muss ja auch eine Kurve bilden.
Linear sieht dass dann so aus:
![image](https://github.com/noahpy/MolSim-SS24/assets/51035972/7e18781d-665d-4e72-add4-61a376b79f25)
Also müssen wir den nächsten neuen Radius immer neu ausrechenen, anstatt ihn per eins zu dekrementieren. Ich überleg mir mal wie wir das machen könnten. Wir müssen dann auch dementsprechend den `getTotalNumbersOfParticles` ändern. Vielleicht können wir die Radien dort schon ausrechenen, iwo speichern und dann hier wiederverwenden?

2024-05-28 06:17 UTC, closed without merging